var manifest = {
    milsym: [
            "web/js/src/armyc2/c2sd/renderer/xml/SinglePointMappingsB.js",
            "web/js/src/armyc2/c2sd/renderer/xml/SymbolConstantsB.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitFontMappingsB.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitConstantsB.js",
            "web/js/src/armyc2/c2sd/renderer/xml/SinglePointMappingsC.js",
            "web/js/src/armyc2/c2sd/renderer/xml/SymbolConstantsC.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitFontMappingsC.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitConstantsC.js",
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/rectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/roundedrectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/ellipse.js",
            "web/js/src/armyc2/c2sd/renderer/so/arc.js",
            "web/js/src/armyc2/c2sd/renderer/so/bcurve.js",
            "web/js/src/armyc2/c2sd/renderer/so/line.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/Color.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/AffiliationColors.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ErrorLogger.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdAttributes.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ImageInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TextInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersUnits.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererSettings.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/singlepointlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/unitfontlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TacticalGraphicLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SinglePointLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitFontLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDimensions.js",
            "web/js/src/armyc2/c2sd/renderer/TacticalGraphicIconRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/SinglePointRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/MilStdIconRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/rectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/roundedrectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/ellipse.js",
            "web/js/src/armyc2/c2sd/renderer/so/arc.js",
            "web/js/src/armyc2/c2sd/renderer/so/bcurve.js",
            "web/js/src/armyc2/c2sd/renderer/so/line.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/Color.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/AffiliationColors.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ErrorLogger.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdAttributes.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersUnits.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererSettings.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/singlepointlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/unitfontlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TacticalGraphicLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SinglePointLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitFontLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDimensions.js",            
            "web/js/src/armyc2/c2sd/renderer/xml/SinglePointSVG.js",
            "web/js/src/armyc2/c2sd/renderer/xml/TacticalGraphicsSVG.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitFontSVG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SPSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TGSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolSVGDimensions.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGTextInfo.js",
            "web/js/src/armyc2/c2sd/renderer/SinglePointSVGRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/TacticalGraphicSVGRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/MilStdSVGRenderer.js",
            "web/js/src/j2slib/java/lang/Class.js",
            "web/js/src/j2slib/java/lang/Double.js",
            "web/js/src/j2slib/java/lang/Integer.js",
            "web/js/src/j2slib/java/lang/System.js",   
            "web/js/src/j2slib/java/util/ArrayList.js",
            "web/js/src/j2slib/java/util/HashMap.js",
            "web/js/src/vincenty/defined.js",
            "web/js/src/vincenty/DeveloperError.js",
            "web/js/src/vincenty/freezeObject.js",
            "web/js/src/vincenty/defineProperties.js",
            "web/js/src/vincenty/defaultValue.js",
            "web/js/src/vincenty/Math.js",
            "web/js/src/vincenty/Cartesian3.js",
            "web/js/src/vincenty/scaleToGeodeticSurface.js",
            "web/js/src/vincenty/Cartographic.js",
            "web/js/src/vincenty/Ellipsoid.js",
            "web/js/src/vincenty/EllipsoidGeodesic.js",			
            "web/js/src/android/graphics/Bitmap.js",
            "web/js/src/android/graphics/Paint.js",
            "web/js/src/android/graphics/Path.js",
            "web/js/src/android/graphics/PointF.js",
            "web/js/src/android/graphics/Rect.js",
            "web/js/src/android/graphics/RectF.js",
            "web/js/src/android/graphics/Typeface.js",
            "web/js/src/j2slib/java/proto.js",
            "web/js/src/armyc2/c2sd/graphics2d/AffineTransform.js",
            "web/js/src/armyc2/c2sd/graphics2d/Area.js",
            "web/js/src/armyc2/c2sd/graphics2d/BasicStroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/BufferedImage.js",
            "web/js/src/armyc2/c2sd/graphics2d/Font.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontMetrics.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontRenderContext.js",
            "web/js/src/armyc2/c2sd/graphics2d/GeneralPath.js",
            "web/js/src/armyc2/c2sd/graphics2d/Graphics2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ImageIO.js",
            "web/js/src/armyc2/c2sd/graphics2d/Line2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/PathIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Polygon.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Shape.js",
            "web/js/src/armyc2/c2sd/graphics2d/Stroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/TextLayout.js",
            "web/js/src/armyc2/c2sd/graphics2d/TexturePaint.js",
            "web/js/src/armyc2/c2sd/graphics2d/Arc2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ArcIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/QuadCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/CubicCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/FlatteningPathIterator.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/CChannelPoints2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/CELineArray.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Channels.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/DISMSupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/POINT2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Shape2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/TacticalLines.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/arraysupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/countsupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/flot.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/lineutility.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/ref.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/Modifier2.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/P1.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/TGLight.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsChannelUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsMETOC.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/mdlGeodesic.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/Color.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/AffiliationColors.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ErrorLogger.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererException.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdSymbol.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdAttributes.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/FillPatterns.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConversion.js",
			"web/js/src/armyc2/c2sd/renderer/utilities/GeoPixelConversion3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConverter3D.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/rectangle.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererSettings.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ShapeInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipPolygon2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipQuad.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityCPOF.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityGE.js",
            "web/js/src/org/gavaghan/geodesy/Angle.js",
            "web/js/src/org/gavaghan/geodesy/Ellipsoid.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCalculator.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCurve.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticMeasurement.js",
            "web/js/src/org/gavaghan/geodesy/GlobalCoordinates.js",
            "web/js/src/org/gavaghan/geodesy/GlobalPosition.js",
            "web/js/src/sec/geo/GeoArc.js",
            "web/js/src/sec/geo/GeoBlock.js",
            "web/js/src/sec/geo/GeoBlock2.js",
            "web/js/src/sec/geo/GeoEllipse.js",
            "web/js/src/sec/geo/GeoPath.js",
            "web/js/src/sec/geo/GeoPoint.js",
            "web/js/src/sec/geo/ShapeObject.js",
            "web/js/src/sec/geo/shape/AExtObject.js",
            "web/js/src/sec/geo/shape/Cake.js",
            "web/js/src/sec/geo/shape/Circle.js",
            "web/js/src/sec/geo/shape/Line.js",
            "web/js/src/sec/geo/shape/Orbit.js",
            "web/js/src/sec/geo/shape/Point.js",
            "web/js/src/sec/geo/shape/Polygon.js",
            "web/js/src/sec/geo/shape/Radarc.js",
            "web/js/src/sec/geo/shape/Polyarc.js",
            "web/js/src/sec/geo/shape/Route.js",
            "web/js/src/sec/geo/shape/Track.js",
            "web/js/src/sec/geo/utilities/StringBuilder.js",
            "web/js/src/sec/sun/awt/geom/Area.js",
            "web/js/src/sec/sun/awt/geom/AreaIterator.js",
            "web/js/src/sec/sun/awt/geom/AreaOp2.js",
            "web/js/src/sec/sun/awt/geom/Arrays.js",
            "web/js/src/sec/sun/awt/geom/ChainEnd.js",
            "web/js/src/sec/sun/awt/geom/Crossings.js",
            "web/js/src/sec/sun/awt/geom/CrossingsObject.js",
            "web/js/src/sec/sun/awt/geom/Curve.js",
            "web/js/src/sec/sun/awt/geom/CurveObject.js",
            "web/js/src/sec/sun/awt/geom/CurveLink.js",
            "web/js/src/sec/sun/awt/geom/EOWindOp.js",
            "web/js/src/sec/sun/awt/geom/NZWindOp.js",
            "web/js/src/sec/sun/awt/geom/Edge.js",
            "web/js/src/sec/sun/awt/geom/Enumeration.js",
            "web/js/src/sec/sun/awt/geom/EvenOdd.js",
            "web/js/src/sec/sun/awt/geom/NonZero.js",
            "web/js/src/sec/sun/awt/geom/Order0.js",
            "web/js/src/sec/sun/awt/geom/Order1.js",
            "web/js/src/sec/sun/awt/geom/Order2.js",
            "web/js/src/sec/sun/awt/geom/Order3.js",
            "web/js/src/sec/sun/awt/geom/SomeOp.js",
            "web/js/src/sec/sun/awt/geom/Vector.js",
            "web/js/src/sec/geo/kml/KmlOptions.js",
            "web/js/src/sec/geo/kml/KmlPolygon.js",
            "web/js/src/sec/geo/kml/KmlRenderer.js",
            "web/js/src/sec/geo/kml/XsltCoordinateWrapper.js",
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGTextInfo.js",
            "web/js/src/sec/web/renderer/MultiPointHandlerSVG.js",
            "web/js/src/sec/web/renderer/utilities/JavaRendererUtilities.js",
            "web/js/src/sec/web/renderer/PointConverter.js",
            "web/js/src/sec/web/renderer/SymbolModifiers.js",
            "web/js/src/sec/web/renderer/GeoPixelConversion.js",
            "web/js/src/sec/web/renderer/MultiPointHandler.js",
            "web/js/src/sec/web/renderer/Shape3DHandler.js",
            "web/js/src/sec/web/renderer/SECWebRenderer.js",
            "web/js/src/Cesium/Core/Matrix3.js",
            "web/js/src/Cesium/Core/VertexFormat.js",
            "web/js/src/Cesium/Core/Quaternion.js",
            "web/js/src/Cesium/Core/IndexDataType.js",
            "web/js/src/Cesium/Core/EllipseGeometryLibrary.js",
            "web/js/src/Cesium/Core/EllipseGeometry.js",            
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/rectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/roundedrectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/ellipse.js",
            "web/js/src/armyc2/c2sd/renderer/so/arc.js",
            "web/js/src/armyc2/c2sd/renderer/so/bcurve.js",
            "web/js/src/armyc2/c2sd/renderer/so/line.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
            "web/js/src/j2slib/java/lang/Class.js",
            "web/js/src/j2slib/java/lang/Double.js",
            "web/js/src/j2slib/java/lang/Integer.js",
            "web/js/src/j2slib/java/lang/System.js",
            "web/js/src/j2slib/java/util/ArrayList.js",
            "web/js/src/j2slib/java/util/HashMap.js",
            "web/js/src/vincenty/defined.js",
            "web/js/src/vincenty/DeveloperError.js",
            "web/js/src/vincenty/freezeObject.js",
            "web/js/src/vincenty/defineProperties.js",
            "web/js/src/vincenty/defaultValue.js",
            "web/js/src/vincenty/Math.js",
            "web/js/src/vincenty/Cartesian3.js",
            "web/js/src/vincenty/scaleToGeodeticSurface.js",
            "web/js/src/vincenty/Cartographic.js",
            "web/js/src/vincenty/Ellipsoid.js",
            "web/js/src/vincenty/EllipsoidGeodesic.js",
            "web/js/src/android/graphics/Bitmap.js",
            "web/js/src/android/graphics/Paint.js",
            "web/js/src/android/graphics/Path.js",
            "web/js/src/android/graphics/PointF.js",
            "web/js/src/android/graphics/Rect.js",
            "web/js/src/android/graphics/RectF.js",
            "web/js/src/android/graphics/Typeface.js",
            "web/js/src/j2slib/java/proto.js",            
            "web/js/src/armyc2/c2sd/graphics2d/AffineTransform.js",
            "web/js/src/armyc2/c2sd/graphics2d/Area.js",
            "web/js/src/armyc2/c2sd/graphics2d/BasicStroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/BufferedImage.js",
            "web/js/src/armyc2/c2sd/graphics2d/Font.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontMetrics.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontRenderContext.js",
            "web/js/src/armyc2/c2sd/graphics2d/GeneralPath.js",
            "web/js/src/armyc2/c2sd/graphics2d/Graphics2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ImageIO.js",
            "web/js/src/armyc2/c2sd/graphics2d/Line2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/PathIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Polygon.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Shape.js",
            "web/js/src/armyc2/c2sd/graphics2d/Stroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/TextLayout.js",
            "web/js/src/armyc2/c2sd/graphics2d/TexturePaint.js",
            
            "web/js/src/armyc2/c2sd/graphics2d/Arc2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ArcIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/QuadCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/CubicCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/FlatteningPathIterator.js",
        
            
            "web/js/src/armyc2/c2sd/JavaLineArray/CChannelPoints2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/CELineArray.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Channels.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/DISMSupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/POINT2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Shape2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/TacticalLines.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/arraysupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/countsupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/flot.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/lineutility.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/ref.js",
        
            
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/Modifier2.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/P1.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/TGLight.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsChannelUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsMETOC.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/mdlGeodesic.js",
        
            
            "web/js/src/armyc2/c2sd/renderer/utilities/Color.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/AffiliationColors.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ErrorLogger.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererException.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdSymbol.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConversion.js",
			"web/js/src/armyc2/c2sd/renderer/utilities/GeoPixelConversion3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConverter3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererSettings.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ShapeInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            
            
            
            "web/js/src/org/gavaghan/geodesy/Angle.js",
            "web/js/src/org/gavaghan/geodesy/Ellipsoid.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCalculator.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCurve.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticMeasurement.js",
            "web/js/src/org/gavaghan/geodesy/GlobalCoordinates.js",
            "web/js/src/org/gavaghan/geodesy/GlobalPosition.js",
            
            "web/js/src/sec/geo/GeoArc.js",
            "web/js/src/sec/geo/GeoBlock.js",
            "web/js/src/sec/geo/GeoBlock2.js",
            "web/js/src/sec/geo/GeoEllipse.js",
            "web/js/src/sec/geo/GeoPath.js",
            "web/js/src/sec/geo/GeoPoint.js",
            "web/js/src/sec/geo/ShapeObject.js",
            
            "web/js/src/sec/geo/shape/AExtObject.js",
            "web/js/src/sec/geo/shape/Cake.js",
            "web/js/src/sec/geo/shape/Circle.js",
            "web/js/src/sec/geo/shape/Line.js",
            "web/js/src/sec/geo/shape/Orbit.js",
            "web/js/src/sec/geo/shape/Point.js",
            "web/js/src/sec/geo/shape/Polygon.js",
            "web/js/src/sec/geo/shape/Radarc.js",
            "web/js/src/sec/geo/shape/Polyarc.js",
            "web/js/src/sec/geo/shape/Route.js",
            "web/js/src/sec/geo/shape/Track.js",
            
            "web/js/src/sec/geo/utilities/StringBuilder.js",
            
            "web/js/src/sec/sun/awt/geom/Area.js",
            "web/js/src/sec/sun/awt/geom/AreaIterator.js",
            "web/js/src/sec/sun/awt/geom/AreaOp2.js",
            "web/js/src/sec/sun/awt/geom/Arrays.js",
            "web/js/src/sec/sun/awt/geom/ChainEnd.js",
            "web/js/src/sec/sun/awt/geom/Crossings.js",
            "web/js/src/sec/sun/awt/geom/CrossingsObject.js",
            "web/js/src/sec/sun/awt/geom/Curve.js",
            "web/js/src/sec/sun/awt/geom/CurveObject.js",
            "web/js/src/sec/sun/awt/geom/CurveLink.js",
            "web/js/src/sec/sun/awt/geom/EOWindOp.js",
            "web/js/src/sec/sun/awt/geom/NZWindOp.js",
            "web/js/src/sec/sun/awt/geom/Edge.js",
            "web/js/src/sec/sun/awt/geom/Enumeration.js",
            "web/js/src/sec/sun/awt/geom/EvenOdd.js",
            "web/js/src/sec/sun/awt/geom/NonZero.js",
            "web/js/src/sec/sun/awt/geom/Order0.js",
            "web/js/src/sec/sun/awt/geom/Order1.js",
            "web/js/src/sec/sun/awt/geom/Order2.js",
            "web/js/src/sec/sun/awt/geom/Order3.js",
            "web/js/src/sec/sun/awt/geom/SomeOp.js",
            "web/js/src/sec/sun/awt/geom/Vector.js",
            
            "web/js/src/sec/geo/kml/KmlOptions.js",
            "web/js/src/sec/geo/kml/KmlPolygon.js",
            "web/js/src/sec/geo/kml/KmlRenderer.js",
            "web/js/src/sec/geo/kml/XsltCoordinateWrapper.js",
            
        
            
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdAttributes.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/FillPatterns.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ImageInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TextInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersUnits.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/singlepointlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/unitfontlookupinfo.js",
        
             
            "web/js/src/armyc2/c2sd/renderer/utilities/TacticalGraphicLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SinglePointLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitFontLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDimensions.js",
        
            
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipPolygon2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipQuad.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityCPOF.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityGE.js",
        
            
            
            "web/js/src/armyc2/c2sd/renderer/TacticalGraphicIconRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/SinglePointRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/MilStdIconRenderer.js",
            
            
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGTextInfo.js",
            "web/js/src/sec/web/renderer/MultiPointHandlerSVG.js",
        
            
            "web/js/src/sec/web/renderer/utilities/JavaRendererUtilities.js",
            "web/js/src/sec/web/renderer/PointConverter.js",
            "web/js/src/sec/web/renderer/SymbolModifiers.js",
            "web/js/src/sec/web/renderer/GeoPixelConversion.js",
            "web/js/src/sec/web/renderer/MultiPointHandlerCanvas.js",
            "web/js/src/sec/web/renderer/MultiPointHandler.js",
            "web/js/src/sec/web/renderer/Shape3DHandler.js",
            "web/js/src/sec/web/renderer/SECWebRenderer.js",
        
            
            "web/js/src/Cesium/Core/Matrix3.js",
            "web/js/src/Cesium/Core/VertexFormat.js",
            "web/js/src/Cesium/Core/Quaternion.js",
            "web/js/src/Cesium/Core/IndexDataType.js",
            "web/js/src/Cesium/Core/EllipseGeometryLibrary.js",
            "web/js/src/Cesium/Core/EllipseGeometry.js",
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/rectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/roundedrectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/ellipse.js",
            "web/js/src/armyc2/c2sd/renderer/so/arc.js",
            "web/js/src/armyc2/c2sd/renderer/so/bcurve.js",
            "web/js/src/armyc2/c2sd/renderer/so/line.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
        
              
            "web/js/src/j2slib/java/lang/Class.js",
            "web/js/src/j2slib/java/lang/Double.js",
            "web/js/src/j2slib/java/lang/Integer.js",
            "web/js/src/j2slib/java/lang/System.js",

            
            "web/js/src/j2slib/java/util/ArrayList.js",
            "web/js/src/j2slib/java/util/HashMap.js",
        
            
            "web/js/src/vincenty/defined.js",
            "web/js/src/vincenty/DeveloperError.js",
            "web/js/src/vincenty/freezeObject.js",
            "web/js/src/vincenty/defineProperties.js",
            "web/js/src/vincenty/defaultValue.js",
            "web/js/src/vincenty/Math.js",
            "web/js/src/vincenty/Cartesian3.js",
            "web/js/src/vincenty/scaleToGeodeticSurface.js",
            "web/js/src/vincenty/Cartographic.js",
            "web/js/src/vincenty/Ellipsoid.js",
            "web/js/src/vincenty/EllipsoidGeodesic.js",

            
            "web/js/src/android/graphics/Bitmap.js",
            "web/js/src/android/graphics/Paint.js",
            "web/js/src/android/graphics/Path.js",
            "web/js/src/android/graphics/PointF.js",
            "web/js/src/android/graphics/Rect.js",
            "web/js/src/android/graphics/RectF.js",
            "web/js/src/android/graphics/Typeface.js",
        
            "web/js/src/j2slib/java/proto.js",
        
            
            "web/js/src/armyc2/c2sd/graphics2d/AffineTransform.js",
            "web/js/src/armyc2/c2sd/graphics2d/Area.js",
            "web/js/src/armyc2/c2sd/graphics2d/BasicStroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/BufferedImage.js",
            "web/js/src/armyc2/c2sd/graphics2d/Font.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontMetrics.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontRenderContext.js",
            "web/js/src/armyc2/c2sd/graphics2d/GeneralPath.js",
            "web/js/src/armyc2/c2sd/graphics2d/Graphics2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ImageIO.js",
            "web/js/src/armyc2/c2sd/graphics2d/Line2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/PathIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Polygon.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Shape.js",
            "web/js/src/armyc2/c2sd/graphics2d/Stroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/TextLayout.js",
            "web/js/src/armyc2/c2sd/graphics2d/TexturePaint.js",
            
            "web/js/src/armyc2/c2sd/graphics2d/Arc2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ArcIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/QuadCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/CubicCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/FlatteningPathIterator.js",
        
            
            "web/js/src/armyc2/c2sd/JavaLineArray/CChannelPoints2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/CELineArray.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Channels.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/DISMSupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/POINT2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Shape2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/TacticalLines.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/arraysupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/countsupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/flot.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/lineutility.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/ref.js",
        
            
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/Modifier2.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/P1.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/TGLight.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsChannelUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsMETOC.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/mdlGeodesic.js",
        
            
            "web/js/src/armyc2/c2sd/renderer/utilities/Color.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/AffiliationColors.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ErrorLogger.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererException.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdSymbol.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdAttributes.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConversion.js",
			"web/js/src/armyc2/c2sd/renderer/utilities/GeoPixelConversion3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConverter3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererSettings.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ShapeInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            
            
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipPolygon2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipQuad.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityCPOF.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityGE.js",
        
            
            
            
            "web/js/src/org/gavaghan/geodesy/Angle.js",
            "web/js/src/org/gavaghan/geodesy/Ellipsoid.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCalculator.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCurve.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticMeasurement.js",
            "web/js/src/org/gavaghan/geodesy/GlobalCoordinates.js",
            "web/js/src/org/gavaghan/geodesy/GlobalPosition.js",
            
            "web/js/src/sec/geo/GeoArc.js",
            "web/js/src/sec/geo/GeoBlock.js",
            "web/js/src/sec/geo/GeoBlock2.js",
            "web/js/src/sec/geo/GeoEllipse.js",
            "web/js/src/sec/geo/GeoPath.js",
            "web/js/src/sec/geo/GeoPoint.js",
            "web/js/src/sec/geo/ShapeObject.js",
            
            "web/js/src/sec/geo/shape/AExtObject.js",
            "web/js/src/sec/geo/shape/Cake.js",
            "web/js/src/sec/geo/shape/Circle.js",
            "web/js/src/sec/geo/shape/Line.js",
            "web/js/src/sec/geo/shape/Orbit.js",
            "web/js/src/sec/geo/shape/Point.js",
            "web/js/src/sec/geo/shape/Polygon.js",
            "web/js/src/sec/geo/shape/Radarc.js",
            "web/js/src/sec/geo/shape/Polyarc.js",
            "web/js/src/sec/geo/shape/Route.js",
            "web/js/src/sec/geo/shape/Track.js",
            
            "web/js/src/sec/geo/utilities/StringBuilder.js",
            
            "web/js/src/sec/sun/awt/geom/Area.js",
            "web/js/src/sec/sun/awt/geom/AreaIterator.js",
            "web/js/src/sec/sun/awt/geom/AreaOp2.js",
            "web/js/src/sec/sun/awt/geom/Arrays.js",
            "web/js/src/sec/sun/awt/geom/ChainEnd.js",
            "web/js/src/sec/sun/awt/geom/Crossings.js",
            "web/js/src/sec/sun/awt/geom/CrossingsObject.js",
            "web/js/src/sec/sun/awt/geom/Curve.js",
            "web/js/src/sec/sun/awt/geom/CurveObject.js",
            "web/js/src/sec/sun/awt/geom/CurveLink.js",
            "web/js/src/sec/sun/awt/geom/EOWindOp.js",
            "web/js/src/sec/sun/awt/geom/NZWindOp.js",
            "web/js/src/sec/sun/awt/geom/Edge.js",
            "web/js/src/sec/sun/awt/geom/Enumeration.js",
            "web/js/src/sec/sun/awt/geom/EvenOdd.js",
            "web/js/src/sec/sun/awt/geom/NonZero.js",
            "web/js/src/sec/sun/awt/geom/Order0.js",
            "web/js/src/sec/sun/awt/geom/Order1.js",
            "web/js/src/sec/sun/awt/geom/Order2.js",
            "web/js/src/sec/sun/awt/geom/Order3.js",
            "web/js/src/sec/sun/awt/geom/SomeOp.js",
            "web/js/src/sec/sun/awt/geom/Vector.js",
            
            "web/js/src/sec/geo/kml/KmlOptions.js",
            "web/js/src/sec/geo/kml/KmlPolygon.js",
            "web/js/src/sec/geo/kml/KmlRenderer.js",
            "web/js/src/sec/geo/kml/XsltCoordinateWrapper.js",
            
        
            
            "web/js/src/armyc2/c2sd/renderer/utilities/FillPatterns.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersUnits.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/singlepointlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/unitfontlookupinfo.js",
        
             
            "web/js/src/armyc2/c2sd/renderer/utilities/TacticalGraphicLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SinglePointLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitFontLookup.js",

            
            
            "web/js/src/armyc2/c2sd/renderer/xml/SinglePointSVG.js",
            "web/js/src/armyc2/c2sd/renderer/xml/TacticalGraphicsSVG.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitFontSVG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SPSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TGSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolSVGDimensions.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGTextInfo.js",
            "web/js/src/armyc2/c2sd/renderer/SinglePointSVGRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/TacticalGraphicSVGRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/MilStdSVGRenderer.js",
        
            
            "web/js/src/sec/web/renderer/utilities/JavaRendererUtilities.js",
            "web/js/src/sec/web/renderer/PointConverter.js",
            "web/js/src/sec/web/renderer/SymbolModifiers.js",
            "web/js/src/sec/web/renderer/GeoPixelConversion.js",
            
            "web/js/src/sec/web/renderer/MultiPointHandlerSVG.js",
            "web/js/src/sec/web/renderer/MultiPointHandler.js",
            "web/js/src/sec/web/renderer/Shape3DHandler.js",
            "web/js/src/sec/web/renderer/SECWebRenderer.js",
        
            
            "web/js/src/Cesium/Core/Matrix3.js",
            "web/js/src/Cesium/Core/VertexFormat.js",
            "web/js/src/Cesium/Core/Quaternion.js",
            "web/js/src/Cesium/Core/IndexDataType.js",
            "web/js/src/Cesium/Core/EllipseGeometryLibrary.js",
            "web/js/src/Cesium/Core/EllipseGeometry.js",
            "web/js/src/armyc2/c2sd/renderer/so/types.js",
            "web/js/src/armyc2/c2sd/renderer/so/utilities.js",
            "web/js/src/armyc2/c2sd/renderer/so/point.js",
            "web/js/src/armyc2/c2sd/renderer/so/rectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/roundedrectangle.js",
            "web/js/src/armyc2/c2sd/renderer/so/ellipse.js",
            "web/js/src/armyc2/c2sd/renderer/so/arc.js",
            "web/js/src/armyc2/c2sd/renderer/so/bcurve.js",
            "web/js/src/armyc2/c2sd/renderer/so/line.js",
            "web/js/src/armyc2/c2sd/renderer/so/path.js",
        
              
            "web/js/src/j2slib/java/lang/Class.js",
            "web/js/src/j2slib/java/lang/Double.js",
            "web/js/src/j2slib/java/lang/Integer.js",
            "web/js/src/j2slib/java/lang/System.js",

            
            "web/js/src/j2slib/java/util/ArrayList.js",
            "web/js/src/j2slib/java/util/HashMap.js",
        
            
            "web/js/src/vincenty/defined.js",
            "web/js/src/vincenty/DeveloperError.js",
            "web/js/src/vincenty/freezeObject.js",
            "web/js/src/vincenty/defineProperties.js",
            "web/js/src/vincenty/defaultValue.js",
            "web/js/src/vincenty/Math.js",
            "web/js/src/vincenty/Cartesian3.js",
            "web/js/src/vincenty/scaleToGeodeticSurface.js",
            "web/js/src/vincenty/Cartographic.js",
            "web/js/src/vincenty/Ellipsoid.js",
            "web/js/src/vincenty/EllipsoidGeodesic.js",

            
            "web/js/src/android/graphics/Bitmap.js",
            "web/js/src/android/graphics/Paint.js",
            "web/js/src/android/graphics/Path.js",
            "web/js/src/android/graphics/PointF.js",
            "web/js/src/android/graphics/Rect.js",
            "web/js/src/android/graphics/RectF.js",
            "web/js/src/android/graphics/Typeface.js",
        
            "web/js/src/j2slib/java/proto.js",
        
            
            "web/js/src/armyc2/c2sd/graphics2d/AffineTransform.js",
            "web/js/src/armyc2/c2sd/graphics2d/Area.js",
            "web/js/src/armyc2/c2sd/graphics2d/BasicStroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/BufferedImage.js",
            "web/js/src/armyc2/c2sd/graphics2d/Font.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontMetrics.js",
            "web/js/src/armyc2/c2sd/graphics2d/FontRenderContext.js",
            "web/js/src/armyc2/c2sd/graphics2d/GeneralPath.js",
            "web/js/src/armyc2/c2sd/graphics2d/Graphics2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ImageIO.js",
            "web/js/src/armyc2/c2sd/graphics2d/Line2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/PathIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point.js",
            "web/js/src/armyc2/c2sd/graphics2d/Point2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Polygon.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle.js",
            "web/js/src/armyc2/c2sd/graphics2d/Rectangle2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/Shape.js",
            "web/js/src/armyc2/c2sd/graphics2d/Stroke.js",
            "web/js/src/armyc2/c2sd/graphics2d/TextLayout.js",
            "web/js/src/armyc2/c2sd/graphics2d/TexturePaint.js",
            
            "web/js/src/armyc2/c2sd/graphics2d/Arc2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/ArcIterator.js",
            "web/js/src/armyc2/c2sd/graphics2d/QuadCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/CubicCurve2D.js",
            "web/js/src/armyc2/c2sd/graphics2d/FlatteningPathIterator.js",
        
            
            "web/js/src/armyc2/c2sd/JavaLineArray/CChannelPoints2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/CELineArray.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Channels.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/DISMSupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/POINT2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/Shape2.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/TacticalLines.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/arraysupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/countsupport.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/flot.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/lineutility.js",
            "web/js/src/armyc2/c2sd/JavaLineArray/ref.js",
        
            
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/Modifier2.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/P1.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/TGLight.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsChannelUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsMETOC.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaTacticalRenderer/mdlGeodesic.js",
        
            
            "web/js/src/armyc2/c2sd/renderer/utilities/Color.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/AffiliationColors.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ErrorLogger.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererException.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdSymbol.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConversion.js",
			"web/js/src/armyc2/c2sd/renderer/utilities/GeoPixelConversion3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/PointConverter3D.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererSettings.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ShapeInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            
            
            
            "web/js/src/org/gavaghan/geodesy/Angle.js",
            "web/js/src/org/gavaghan/geodesy/Ellipsoid.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCalculator.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticCurve.js",
            "web/js/src/org/gavaghan/geodesy/GeodeticMeasurement.js",
            "web/js/src/org/gavaghan/geodesy/GlobalCoordinates.js",
            "web/js/src/org/gavaghan/geodesy/GlobalPosition.js",
            
            "web/js/src/sec/geo/GeoArc.js",
            "web/js/src/sec/geo/GeoBlock.js",
            "web/js/src/sec/geo/GeoBlock2.js",
            "web/js/src/sec/geo/GeoEllipse.js",
            "web/js/src/sec/geo/GeoPath.js",
            "web/js/src/sec/geo/GeoPoint.js",
            "web/js/src/sec/geo/ShapeObject.js",
            
            "web/js/src/sec/geo/shape/AExtObject.js",
            "web/js/src/sec/geo/shape/Cake.js",
            "web/js/src/sec/geo/shape/Circle.js",
            "web/js/src/sec/geo/shape/Line.js",
            "web/js/src/sec/geo/shape/Orbit.js",
            "web/js/src/sec/geo/shape/Point.js",
            "web/js/src/sec/geo/shape/Polygon.js",
            "web/js/src/sec/geo/shape/Radarc.js",
            "web/js/src/sec/geo/shape/Polyarc.js",
            "web/js/src/sec/geo/shape/Route.js",
            "web/js/src/sec/geo/shape/Track.js",
            
            "web/js/src/sec/geo/utilities/StringBuilder.js",
            
            "web/js/src/sec/sun/awt/geom/Area.js",
            "web/js/src/sec/sun/awt/geom/AreaIterator.js",
            "web/js/src/sec/sun/awt/geom/AreaOp2.js",
            "web/js/src/sec/sun/awt/geom/Arrays.js",
            "web/js/src/sec/sun/awt/geom/ChainEnd.js",
            "web/js/src/sec/sun/awt/geom/Crossings.js",
            "web/js/src/sec/sun/awt/geom/CrossingsObject.js",
            "web/js/src/sec/sun/awt/geom/Curve.js",
            "web/js/src/sec/sun/awt/geom/CurveObject.js",
            "web/js/src/sec/sun/awt/geom/CurveLink.js",
            "web/js/src/sec/sun/awt/geom/EOWindOp.js",
            "web/js/src/sec/sun/awt/geom/NZWindOp.js",
            "web/js/src/sec/sun/awt/geom/Edge.js",
            "web/js/src/sec/sun/awt/geom/Enumeration.js",
            "web/js/src/sec/sun/awt/geom/EvenOdd.js",
            "web/js/src/sec/sun/awt/geom/NonZero.js",
            "web/js/src/sec/sun/awt/geom/Order0.js",
            "web/js/src/sec/sun/awt/geom/Order1.js",
            "web/js/src/sec/sun/awt/geom/Order2.js",
            "web/js/src/sec/sun/awt/geom/Order3.js",
            "web/js/src/sec/sun/awt/geom/SomeOp.js",
            "web/js/src/sec/sun/awt/geom/Vector.js",
            
            "web/js/src/sec/geo/kml/KmlOptions.js",
            "web/js/src/sec/geo/kml/KmlPolygon.js",
            "web/js/src/sec/geo/kml/KmlRenderer.js",
            "web/js/src/sec/geo/kml/XsltCoordinateWrapper.js",
            
        
            
            "web/js/src/armyc2/c2sd/renderer/utilities/MilStdAttributes.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/FillPatterns.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/RendererUtilities.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ImageInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TextInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/ModifiersUnits.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/singlepointlookupinfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/unitfontlookupinfo.js",
        
             
            "web/js/src/armyc2/c2sd/renderer/utilities/TacticalGraphicLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitDefTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SinglePointLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitFontLookup.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolDimensions.js",
        
            
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipPolygon2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsClipQuad.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsRenderer2.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtility.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityCPOF.js",
            "web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityGE.js",
        
            
            
            "web/js/src/armyc2/c2sd/renderer/TacticalGraphicIconRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/SinglePointRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/MilStdIconRenderer.js",
            
            
            "web/js/src/armyc2/c2sd/renderer/xml/SinglePointSVG.js",
            "web/js/src/armyc2/c2sd/renderer/xml/TacticalGraphicsSVG.js",
            "web/js/src/armyc2/c2sd/renderer/xml/UnitFontSVG.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SPSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/TGSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/UnitSVGTable.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SymbolSVGDimensions.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGInfo.js",
            "web/js/src/armyc2/c2sd/renderer/utilities/SVGTextInfo.js",
            "web/js/src/armyc2/c2sd/renderer/SinglePointSVGRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/TacticalGraphicSVGRenderer.js",
            "web/js/src/armyc2/c2sd/renderer/MilStdSVGRenderer.js",
            
            
            "web/js/src/sec/web/renderer/utilities/JavaRendererUtilities.js",
            "web/js/src/sec/web/renderer/PointConverter.js",
            "web/js/src/sec/web/renderer/SymbolModifiers.js",
            "web/js/src/sec/web/renderer/GeoPixelConversion.js",
            "web/js/src/sec/web/renderer/MultiPointHandlerCanvas.js",
            "web/js/src/sec/web/renderer/MultiPointHandlerSVG.js",
            "web/js/src/sec/web/renderer/MultiPointHandler.js",
            "web/js/src/sec/web/renderer/Shape3DHandler.js",
            "web/js/src/sec/web/renderer/SECWebRenderer.js",
                        
            
            "web/js/src/Cesium/Core/Matrix3.js",
            "web/js/src/Cesium/Core/VertexFormat.js",
            "web/js/src/Cesium/Core/Quaternion.js",
            "web/js/src/Cesium/Core/IndexDataType.js",
            "web/js/src/Cesium/Core/EllipseGeometryLibrary.js",
            "web/js/src/Cesium/Core/EllipseGeometry.js",
    ]
};

module.exports = manifest